name: 09 - Using Functions
on:
  workflow_dispatch:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        if: github.event.pull_request
        run: echo "PR Title: ${{ github.event.pull_request.title }}"

      - name: Print PR labels
        if: github.event.pull_request
        run: echo "PR Labls: ${{ toJSON(github.event.pull_request.labels)}}"
        
      - name: Sleep for 20 seconds
        run: sleep 20
    
      - name: Failing step
        run: exit 1

      - name: I will be skipped
        if: success()
        run: echo "I will print if previous steps succeed."

      - name: I will execute
        if: failure()
        run: echo "I will print if any previous step fails."

      - name: I will execute
        if: "!canceled()"
        run: echo "I will always print, except when the workflow is cancelled."

      - name: I will execute when cancelled
        if: "cancelled()"
